package eduAI.trace.lib;

public enum LibDesignPattern {
	NONE,
	MESSAGE_PROCESSING,
	PROVIDER_EXECUTION,
	CONTEXT_MAINTENANCE,
	COMPACTION_PIPELINE,
	CONVERSATION_RECALL,
	RESPONSE_CACHE,
	SINGLE_MODEL_REQUEST_PROCESSING
}
